title: "Data Analyst"
theme: jekyll-theme-minimal
github_username: false  # oculta "View My GitHub Profile"

# Header izquierdo (HTML permitido)
description: |-
  <div style="margin-top:6px;">
    <img src="https://avatars.githubusercontent.com/DANTEDUPEYRON21?size=512"
         alt="Dante Dupeyron"
         style="width:180px;height:180px;border-radius:50%;object-fit:cover;"/>
    <p style="margin:10px 0 2px 0;"><strong>Dante Dupeyron</strong> 路 Data Analyst Junior</p>
    <p style="margin:0 0 10px 0; opacity:.85;">Transformo datos en decisiones claras 路 Python 路 SQL 路 Tableau</p>
    <div style="display:flex; gap:8px; flex-wrap:wrap;">
      <a href="https://www.linkedin.com/in/dantedupeyron/" target="_blank"
         style="padding:8px 12px;background:#0A66C2;color:#fff;border-radius:8px;text-decoration:none;">LinkedIn</a>
      <a href="https://github.com/DANTEDUPEYRON21" target="_blank"
         style="padding:8px 12px;background:#333;color:#fff;border-radius:8px;text-decoration:none;">GitHub</a>
      <a href="/DA_CV_DANTE_DUPEYRON (2).pdf" target="_blank"
         style="padding:8px 12px;background:#28a745;color:#fff;border-radius:8px;text-decoration:none;">CV (PDF)</a>
      <a href="mailto:dadupun79@gmail.com"
         style="padding:8px 12px;background:#EA4335;color:#fff;border-radius:8px;text-decoration:none;">Email</a>
    </div>
  </div>



